name: quickbooks
description: A package to talk to the quickbook api.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.0+2
  collection: ^1.17.2
  http: ^0.13.6
  intl: ^0.18.1
  oauth2: ^2.0.1
  xml: ^6.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
